### ISSUE TITLE
Add optional redis auth to karton

### ISSUE THREAD

**Issue by msm-code** [CERT-Polska/karton#107]
There are few situations where authentication to the Karton's central Redis server is desirable:

1. Karton is deployed on the public network, and Redis server has to be accessible to other services (but obviously not to the whole Internet)
2. Defence in depth, or more complex access control (for example, readonly users)

This change should be relative easy to implement, and we already require auth to the central minio server.

**Comment by nazywam** [comment]
Closed by #114
