### ISSUE TITLE
Grafana integration: need to mention it in documentation

### ISSUE THREAD

**Issue by rakovskij-stanislav** [CERT-Polska/karton#128]
https://github.com/CERT-Polska/karton/pull/115

You said that there is prometeus-like feed from karton. I ask for small instruction about it to integrate this metrics to prometeus/grafana.

**Comment by nazywam** [comment]
Metrics are stored in redis and exposed by karton-dashboard: https://github.com/CERT-Polska/karton-dashboard/blob/master/karton/dashboard/app.py#L187

You should be able to process them by pointing the system at that path.

I'll add this as section in the documentation when I get a chance

**Comment by rakovskij-stanislav** [comment]
Okay, thank you)

**Comment by nazywam** [comment]
I'll keep this open as a reminder ;)

**Comment by rakovskij-stanislav** [comment]
Okay, not problem :)

**Comment by rakovskij-stanislav** [comment]
https://github.com/CERT-Polska/karton-dashboard/pull/45

Hi. Please consider to add grafana formulas you used in screenshot https://github.com/CERT-Polska/karton-dashboard/blob/master/img/grafana.png for faster grafana configuration.

**Comment by nazywam** [comment]
@rakovskij-stanislav Added a few query examples here: https://github.com/CERT-Polska/karton-dashboard/pull/48
