### ISSUE TITLE
Karton Task tree

### ISSUE THREAD

**Issue by rakovskij-stanislav** [CERT-Polska/karton#129]
I use pydot to make graph of task analysis using root_uid. For now i'm storing all events using log consumer, so this way I can use this info to write the graph. Is there any methods using karton-core to get analysis tree by root_uid - or an info about completed task will be deleted by karton-core?

**Comment by rakovskij-stanislav** [comment]
```
>>> from karton.core import Config as KartonConfig
>>> from karton.core import Producer, Resource, Task
>>> from karton.core.backend import KartonBackend
>>> from karton.core.inspect import KartonState
>>> from karton.core.task import TaskPriority
>>> karton_config = KartonConfig()
>>> karton_backend = KartonBackend(karton_config)
>>> state = KartonState(karton_backend)
>>> state
<karton.core.inspect.KartonState object at 0x7fe337e5d2b0>
>>> analysis = state.analyses.get("4afc2e68-3202-4c8b-a2c0-b44eb3501133")
>>> analysis
>>> type(analysis)
<class 'NoneType'>
>>> from karton.core.inspect import KartonAnalysis
>>> KartonAnalysis("4afc2e68-3202-4c8b-a2c0-b44eb3501133")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __init__() missing 2 required positional arguments: 'tasks' and 'state'
>>> karton_backend.get_task("4afc2e68-3202-4c8b-a2c0-b44eb3501133")
>>>
```

I tried to use things from various parts of code - buy nothing works for completed task

**Comment by chivay** [comment]
> I use pydot to make graph of task analysis using root_uid. For now i'm storing all events using log consumer, so this way I can use this info to write the graph. 

We use the same method in our karton deployment at CERT.pl. 

>Is there any methods using karton-core to get analysis tree by root_uid - or an info about completed task will be deleted by karton-core?

Completed tasks are garbage collected by karton-system so they won't appear in Redis. We already have feature that could in theory work for tree reconstruction - task signaling, implemented in https://github.com/CERT-Polska/karton/commit/31f5baf39e157ad053618c51fa99ff8519391296 . Although, the tasks it sends should be extended with additional payload to enable this.

**Comment by rakovskij-stanislav** [comment]
Okay, it sounds like I still need to save logs)
Thank you
