### ISSUE TITLE
Unittest - LocalResource vs RemoteResource

### ISSUE THREAD

**Issue by questionaier** [CERT-Polska/karton#149]
Hello,
I was trying to make some tests for my plugins in the way described here:
[testing-resources](https://github.com/CERT-Polska/karton/blob/158d07960d8cd39dee8771af719f560df93b3212/docs/unit_tests.rst#testing-resources)

however when we create fake resource in this way:

```
        # create fake, mini-independent resources
        input_sample = Resource("sample.txt", input_data)
```

it becomes LocalResource. And then when we create task from it, pass it to our karton with:

```
        # dry-run the fake task on the wrapped karton system
        results = self.run_task(task)
```

it is still LocalResource. Being this it does not have "download_temporary_file" method, which is used in plugins (e.g. Strings plugin - example of yours [my-first-karton-task](https://github.com/CERT-Polska/karton-playground#3-my-first-karton-task) ). When I run unittest it throws "AttributeError: 'LocalResource' object has no attribute 'download_temporary_file'" because of that.
1) Am I doing something wrong or your example isn't accurate?
2) Can you make some fully covered example with testing-resources and using download_temporary_file method in plugin?
3) Is it dependent on karton-core version?

Thanks for any answers

**Comment by psrok1** [comment]
Hi @questionaier!

Sorry for late answer. It's a shame but test utils are actually broken. After introduction of KartonBackend I've reimplemented `karton.core.test` but resource upload mock was left unimplemented.

It will be fixed in https://github.com/CERT-Polska/karton/pull/180
