### ISSUE TITLE
Consumer filter: subscribe to every event if 'filters' field is empty

### ISSUE THREAD

**Issue by rakovskij-stanislav** [CERT-Polska/karton#151]
Allow a possibility to subscribe to every event

**Comment by psrok1** [comment]
Following the filter logic, correct way is to use `filters = [{}]` and it already works in current Karton version.

`filters = []` is already used by our team to turn off routing to the queue and to let the consumer process all of the tasks that are left.

I've added that pattern into documentation in #179.
