### ISSUE TITLE
Remove remnants of MinIO

### ISSUE THREAD

**Issue by chivay** [CERT-Polska/karton#191]
Karton was migrated to boto3, however there are still a few places where mentions of MinIO remain (including the readme).

```
$ rg -i minio | wc -l
46
```

**Comment by nazywam** [comment]
There will definitely be some minio references -> mainly because we still use MinIO as a recommended s3 storage and we still have to deal with the deprecatead `[minio]` section.

That being said, I've noticed a few unneeded references. Will take core of those :+1:

**Comment by cugu** [comment]
MinIO is still mentioned on GitHub in the About section https://github.com/CERT-Polska/karton

See: 
![Bildschirmfoto 2022-08-27 um 12 40 47](https://user-images.githubusercontent.com/653777/187026635-4d5305ce-ce2b-4c20-8919-a215ee30f8d3.png)
 
ripgrep won't find that 😉

**Comment by nazywam** [comment]
Fixed, thanks!
