### ISSUE TITLE
unit test failing after upgrade to karton 5.0.0

### ISSUE THREAD

**Issue by ropgadgets** [CERT-Polska/karton#199]
Hi,

I've run into a weird race condition like issue when running unit tests on some of my kartons after upgrading to karton-core 5.0.0.  It appears that the `resource._content` doesn't always finish populating by the time `KartonTestCase.get_resource_sha256` is called via `KartonTestCase.assertTasksEqual` from my test case.

The error I get is `TypeError: object supporting the buffer API required` on line 150 in karton/core/test.py.  Setting a breakpoint on line 150 and inspecting with the debugger shows that `resource._content` is `None` when it initially arrives at the breakpoint; however, if I wait a few seconds, I can see the `_content` variable populate with the correct data in the debugger, and then the unit test is able to pass as expected.

https://github.com/CERT-Polska/karton/blob/master/karton/core/test.py#L150

**Comment by conitrade-as** [comment]
Just hit the same issue. Looks like in the 5.x.x code base now uses instances of `RemoteResource`. For which direct access to `_content` does not work when it is not downloaded.

https://github.com/CERT-Polska/karton/blob/master/karton/core/test.py#L150 should use `h.update(cast(bytes, resource.content))`.

In the meantime the following works in test cases:
```
res = self.run_task(task)
for task in res:
    task.get_payload('sample').download()
```
