### ISSUE TITLE
Ensure compatibility with AWS S3

### ISSUE THREAD

**Issue by chivay** [CERT-Polska/karton#64]

**Comment by alex-ilgayev** [comment]
I would add an option for IAM authentication without credentials similar to this recently merged PR:
https://github.com/CERT-Polska/mwdb-core/pull/443

**Comment by alex-ilgayev** [comment]
Hey @nazywam 
We are working quite a while with S3 instead of Minio, and it is working as intended.
So I suggest you can close this issue.

**Comment by nazywam** [comment]
Will do, thanks!
