### ISSUE TITLE
Expose consumer version in KartonBind

### ISSUE THREAD

**Issue by psrok1** [CERT-Polska/karton#69]
Currently we expose only the library version used by Karton service. Consumer version can be exposed as well and shown in API.

**Comment by nazywam** [comment]
:+1:

I've taken a look and the only problem I see is that the `version` fieldname is already used for keeping the karton library version.
I don't think breaking compatibility would be very wise there so we probably have to decide on another name.
2 possible names I've came up with:
 * `service_version`
 * `consumer_version`
